name: ubi_container_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.10.0 # Asegúrate de que esta versión sea correcta
  latlong2: ^0.9.1  # Actualiza a la última versión disponible
  carousel_slider: ^5.1.1  # Actualiza a la última versión disponible
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.2  # Actualiza a la última versión disponible
  permission_handler: ^11.0.0 # Manejo completo de permisos (ubicación, etc.)
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3  # Actualiza a la última versión disponible
  uuid: ^4.5.1
  http: ^1.5.0  
  image_picker: ^1.0.5  
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets que tengas en tu proyecto
  # assets:
  #   - assets/images/
  #   - assets/data/
  #   - assets/icons/

  # Fuentes personalizadas si las tienes
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
